/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import model.User;
import util.DatabaseConnector;


/**
 *
 * @author Jeel
 */
public class FormPanel extends javax.swing.JPanel {

    /**
     * Creates new form FormPanel
     */
    private JPanel bottompanel;
    public FormPanel(JPanel inputpanel) {
        initComponents();
        this.bottompanel = inputpanel;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        lbl_title = new javax.swing.JLabel();
        lbl_fname = new javax.swing.JLabel();
        lbl_age = new javax.swing.JLabel();
        txt_fname = new javax.swing.JTextField();
        txt_age = new javax.swing.JTextField();
        btn_submit = new javax.swing.JButton();
        error_fname = new javax.swing.JLabel();
        error_lname = new javax.swing.JLabel();
        error_age = new javax.swing.JLabel();
        error_email = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        error_ptype = new javax.swing.JLabel();
        error_gender = new javax.swing.JLabel();

        lbl_title.setFont(new java.awt.Font("Cambria", 1, 16)); // NOI18N
        lbl_title.setText("Patient Registration Form");

        lbl_fname.setText("Name:");

        lbl_age.setText("Age");

        txt_fname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_fnameKeyReleased(evt);
            }
        });

        txt_age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_ageKeyReleased(evt);
            }
        });

        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        error_fname.setForeground(new java.awt.Color(255, 0, 0));

        error_lname.setForeground(new java.awt.Color(255, 0, 0));

        error_age.setForeground(new java.awt.Color(255, 0, 0));

        error_email.setForeground(new java.awt.Color(255, 0, 0));

        error_message.setForeground(new java.awt.Color(255, 0, 0));

        error_ptype.setForeground(new java.awt.Color(255, 0, 0));

        error_gender.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(lbl_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_age)
                            .addComponent(lbl_fname))
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(error_ptype, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_email, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_lname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_submit, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(txt_age)
                            .addComponent(txt_fname)
                            .addComponent(error_fname, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_age, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(error_message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(error_gender, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(55, 55, 55)))))
                .addContainerGap(143, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lbl_title, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fname)
                    .addComponent(txt_fname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(error_fname)
                .addGap(27, 27, 27)
                .addComponent(error_lname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_age)
                    .addComponent(txt_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(error_age)
                .addGap(34, 34, 34)
                .addComponent(error_email)
                .addGap(18, 18, 18)
                .addComponent(btn_submit)
                .addGap(69, 69, 69)
                .addComponent(error_message)
                .addGap(28, 28, 28)
                .addComponent(error_ptype)
                .addGap(34, 34, 34)
                .addComponent(error_gender)
                .addContainerGap(188, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        // TODO add your handling code here:
        User newUser = new User();
        try{
          newUser.setAge(Integer.parseInt(txt_age.getText()));
          newUser.setName(txt_fname.getText());
          
          DatabaseConnector.addUser(newUser);
          
          JOptionPane.showMessageDialog(null, "User Registered Successfully", "Successful Registration", JOptionPane.PLAIN_MESSAGE);
        }
        catch(Exception e){
        JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void txt_fnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_fnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z]{2,20}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_fname.getText());
        if(!match.matches()){
            error_fname.setText("Please enter Only Alphabets in first name");
        }
        else {
            error_fname.setText(null);
        }
    }//GEN-LAST:event_txt_fnameKeyReleased

    private void txt_ageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_ageKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,110}$";
        Pattern pat = Pattern.compile(PATTERN);
        Matcher match = pat.matcher(txt_age.getText());
        if(!match.matches()){
            error_age.setText("Please enter only number, no invalid characters allowed");
        }
        else {
            error_age.setText(null);
        }
    }//GEN-LAST:event_txt_ageKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_submit;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel error_age;
    private javax.swing.JLabel error_email;
    private javax.swing.JLabel error_fname;
    private javax.swing.JLabel error_gender;
    private javax.swing.JLabel error_lname;
    private javax.swing.JLabel error_message;
    private javax.swing.JLabel error_ptype;
    private javax.swing.JLabel lbl_age;
    private javax.swing.JLabel lbl_fname;
    private javax.swing.JLabel lbl_title;
    private javax.swing.JTextField txt_age;
    private javax.swing.JTextField txt_fname;
    // End of variables declaration//GEN-END:variables
        String filename;

}
